import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profileWomen from "../../public/images/profile/profile-1.png";
import AnimatedText from "@/components/stylesComponents/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import Hireme from "@/components/Hireme";
import lightBuld from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dev - Erika</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark dark:text-light w-full min-h-screen  md:items-start">
        <Layout className="pt-0 md:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profileWomen}
                alt="A girl"
                className="w-full h-auto 2xl:px-[120px] xl:px-[80px] md:px-[200px] sm:px-[170px] xs:px-[40px] rounded-b-[50%] lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Convertir la visión en realidad con código y diseño"
                className="!text-left 2xl:!text-6xl xl:!text-5xl lg:!text-center lg:!text-4xl md:!text-3xl sm:text-2xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                Como desarrolladora full-stack, me dedico a convertir ideas en
                aplicaciones web innovadoras. Explore mis últimos proyectos,
                mostrando mi experiencia en React.js y desarrollo web.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center ">
                <Link
                  href="/dummy.pdf"
                  target={"_black"}
                  className="flex items-center  bg-dark text-light p-2.5 px-4 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border border-solid border-transparent hover:border-dark dark:text-dark dark:bg-light dark:hover:border-light dark:hover:text-light dark:hover:bg-dark md:p-2 xs:px-2 md:px-4 md:text-base "
                  download={true}
                >
                  {"Descargar CV"}
                  <LinkArrow className={"ml-1"} />
                </Link>
                <Link
                  href="/"
                  target={"_black"}
                  className="ml-4 text-lg font-medium capitalize text-dark dark:text-light underline  md:text-base"
                >
                  Contacto
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <Hireme />
        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={lightBuld} alt="ErikAviles" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
