import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profileWomen from "../../public/images/profile/profile-1.png";
import AnimatedText from "@/components/stylesComponents/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import Hireme from "@/components/Hireme";
import lightBuld from "../../public/images/svgs/miscellaneous_icons_1.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dev - Erika</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark dark:text-light w-full min-h-screen">
        <Layout>
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2 self-center ">
              <Image
                src={profileWomen}
                alt="A girl"
                className="w-full h-auto px-[120px] rounded-b-[50%]"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center ">
              <AnimatedText
                text="Convertir la visión en realidad con código y diseño"
                className="!text-left"
              />
              <p className="my-4 text-base font-medium">
                Como desarrolladora full-stack, me dedico a convertir ideas en
                aplicaciones web innovadoras. Explore mis últimos proyectos,
                mostrando mi experiencia en React.js y desarrollo web.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/dummy.pdf"
                  target="_black"
                  className="w-full flex justify-center bg-dark text-light p-2 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border border-solid border-transparent hover:border-dark dark:text-dark dark:bg-light dark:hover:border-light dark:hover:text-light dark:hover:bg-dark"
                  download={true}
                >
                  Descargar CV
                  <LinkArrow className="w-4 ml-2" />
                </Link>
                <Link
                  href="/"
                  target="_black"
                  className="ml-4 text-lg font-medium capitalize text-dark dark:text-light  underline"
                >
                  Contacto
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <Hireme />
        <div className="absolute right-8 bottom-8 inline-block w-24">
          <Image src={lightBuld} alt="ErikAviles" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
